name: LLVM Toolchain
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 17 * * 3'

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: Actions
    steps:
      - name: Download scripts
        uses: actions/checkout@v3

      - name: Get deps
        run: ./ci.sh deps

      - name: Deploy builder
        env:
          LLVM_NAME: ${{ secrets.LLVM_NAME}}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_EMAIL: ${{ secrets.GITLAB_EMAIL }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_PUSH_REPO_URL: ${{ secrets.GITLAB_PUSH_REPO_URL }}
          GITLAB_SCRIPT_REPO_URL: ${{ secrets.GITLAB_SCRIPT_REPO_URL }}
        run: ./build-tc.sh
